# Generated by Django 6.0.6 on 2026-07-06 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core_ref', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_projet', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(choices=[('Ouvert', 'Ouvert'), ('En cours', 'En cours'), ('En attente', 'En attente'), ('Suspendu', 'Suspendu'), ('Clôturé', 'Clôturé'), ('Annulé', 'Annulé'), ('Finalisé', 'Finalisé')], default='Ouvert', max_length=30)),
                ('priorite', models.CharField(blank=True, choices=[('Critique', 'Critique'), ('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Basse', 'Basse')], max_length=30)),
                ('date_debut_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_debut_reelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_reel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('progression_calculee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poids_portefeuille', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('earned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('est_generique', models.BooleanField(default=False)),
                ('est_lecture_seule', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('conteneur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='core_ref.conteneur')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_crees', to=settings.AUTH_USER_MODEL)),
                ('entite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.entite')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_modifies', to=settings.AUTH_USER_MODEL)),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.pays')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_responsable', to=settings.AUTH_USER_MODEL)),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.secteur')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.site')),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='MigrationConteneurLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_migration', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('conteneur_cible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations_cible', to='core_ref.conteneur')),
                ('conteneur_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='migrations_source', to='core_ref.conteneur')),
                ('migre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
            ],
            options={
                'verbose_name': 'Log Migration Conteneur',
                'ordering': ['-date_migration'],
            },
        ),
        migrations.CreateModel(
            name='ProjetEntite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_entite', models.CharField(blank=True, max_length=100)),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.entite')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
            ],
            options={
                'unique_together': {('projet', 'entite')},
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='entites_associees',
            field=models.ManyToManyField(blank=True, related_name='projets_associes', through='projects.ProjetEntite', to='accounts.entite'),
        ),
        migrations.CreateModel(
            name='ProjetSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projet')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_ref.site')),
            ],
            options={
                'unique_together': {('projet', 'site')},
            },
        ),
        migrations.AddField(
            model_name='projet',
            name='sites_associes',
            field=models.ManyToManyField(blank=True, related_name='projets_associes', through='projects.ProjetSite', to='core_ref.site'),
        ),
    ]
