# Generated by Django 6.0.6 on 2026-07-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('methode', models.CharField(choices=[('CPI', 'EAC basé sur CPI'), ('SPI', 'Projection planning'), ('HYBRID', 'Modèle hybride')], default='CPI', max_length=20)),
                ('poids_cout', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('poids_planning', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('mise_a_jour_auto', models.BooleanField(default=True)),
                ('date_derniere_calcul', models.DateTimeField(blank=True, null=True)),
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_rule', to='projects.projet')),
            ],
        ),
        migrations.CreateModel(
            name='ProjetCurvePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('granularite', models.CharField(choices=[('DAY', 'Jour'), ('WEEK', 'Semaine'), ('MONTH', 'Mois'), ('QUARTER', 'Trimestre'), ('SEMESTER', 'Semestre'), ('YEAR', 'Année')], default='MONTH', max_length=20)),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('earned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('forecast_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curve_points', to='projects.projet')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('projet', 'date', 'granularite')},
            },
        ),
    ]
