# Generated by Django 6.0.6 on 2026-07-16 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_forecastrule_projetcurvepoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='migrationconteneurlog',
            options={'ordering': ['-date_operation'], 'verbose_name': 'Log Migration Conteneur'},
        ),
        migrations.RenameField(
            model_name='migrationconteneurlog',
            old_name='date_migration',
            new_name='date_operation',
        ),
        migrations.AddField(
            model_name='migrationconteneurlog',
            name='type_operation',
            field=models.CharField(choices=[('MIGRATION', 'Migration'), ('DELETE', 'Suppression logique'), ('RESTORE', 'Restauration')], default='MIGRATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='migrationconteneurlog',
            name='migre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrations_conteneurs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='migrationconteneurlog',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.projet'),
        ),
    ]
