# Generated by Django 6.0.6 on 2026-07-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ref', '0002_alter_phase_options_phase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['ordre'], 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AddField(
            model_name='discipline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='discipline',
            name='domaine',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='discipline',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans le référentiel des disciplines EPC.", unique=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='discipline',
            table='core_ref_discipline',
        ),
    ]
