# Generated by Django 6.0.6 on 2026-07-06 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseDocumentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('libelle', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cycle_simplifie', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Classe Documentaire',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Conteneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('est_archive', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocTypeCorrespondance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de Document Correspondance',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pays', models.CharField(max_length=5, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='StatutCycleVie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('est_terminal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Statut Cycle de Vie',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocTypeTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('classe_num', models.IntegerField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.discipline')),
            ],
            options={
                'verbose_name': 'Type de Document Technique',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_site', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='core_ref.pays')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_secteur', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secteurs', to='core_ref.site')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Systeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_systeme', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systemes', to='core_ref.secteur')),
            ],
            options={
                'verbose_name': 'Système',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SousSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sous_systeme', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sous_systemes', to='core_ref.systeme')),
            ],
            options={
                'verbose_name': 'Sous-Système',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_tag', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type_equipement', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.discipline')),
                ('sous_systeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.soussysteme')),
            ],
            options={
                'ordering': ['code_tag'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStatut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_num', models.IntegerField()),
                ('ordre', models.IntegerField()),
                ('est_statut_final', models.BooleanField(default=False)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_ref.phase')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_ref.statutcyclevie')),
            ],
            options={
                'verbose_name': 'Séquence de Statut',
                'ordering': ['phase', 'classe_num', 'ordre'],
                'unique_together': {('phase', 'classe_num', 'ordre')},
            },
        ),
    ]
