# Generated by Django 6.0.6 on 2026-07-15 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ref', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['ordre'], 'verbose_name': 'Phase projet', 'verbose_name_plural': 'Phases projet'},
        ),
        migrations.AddField(
            model_name='phase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='phase',
            field=models.CharField(default=1, help_text="Nom complet de la phase (identique à 'nom').", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='phase',
            name='ordre',
            field=models.PositiveSmallIntegerField(help_text="Ordre d'exécution dans le cycle de vie du projet.", unique=True),
        ),
        migrations.AlterModelTable(
            name='phase',
            table='core_ref_phase',
        ),
    ]
