# Generated by Django 6.0.6 on 2026-07-15 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ref', '0003_alter_discipline_options_discipline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctypetechnique',
            options={'ordering': ['code'], 'verbose_name': 'Type de Document Technique', 'verbose_name_plural': 'Types de Documents Techniques'},
        ),
        migrations.RemoveField(
            model_name='doctypetechnique',
            name='discipline',
        ),
        migrations.AddField(
            model_name='doctypetechnique',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctypetechnique',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctypetechnique',
            name='discipline_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types_documents_principaux', to='core_ref.discipline'),
        ),
        migrations.AddField(
            model_name='doctypetechnique',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctypetechnique',
            name='libelle',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='doctypetechnique',
            table='core_ref_doctypetechnique',
        ),
    ]
