# Generated by Django 6.0.6 on 2026-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ref', '0004_alter_doctypetechnique_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctypetechnique',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
