# Generated by Django 6.0.6 on 2026-07-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ref', '0005_doctypetechnique_ordre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctypetechnique',
            options={'ordering': ['ordre', 'code'], 'verbose_name': 'Type de Document Technique', 'verbose_name_plural': 'Types de Documents Techniques'},
        ),
        migrations.AlterField(
            model_name='doctypetechnique',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans le référentiel documentaire."),
        ),
        migrations.AlterField(
            model_name='phase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
