# Generated by Django 6.0.6 on 2026-07-15 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ref', '0006_alter_doctypetechnique_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discipline',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage."),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
