# Generated by Django 6.0.6 on 2026-07-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ref', '0007_alter_discipline_code_alter_discipline_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Originator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('num_po', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
                ('est_archive', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
