# Generated by Django 6.0.6 on 2026-07-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ref', '0008_originator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='originator',
            name='nom_entreprise',
            field=models.CharField(default='[nom Entreprise]', max_length=100),
        ),
        migrations.AlterField(
            model_name='originator',
            name='num_po',
            field=models.CharField(default='[PO-Common-0000]', max_length=25, unique=True),
        ),
    ]
