# Generated by Django 6.0.6 on 2026-07-16 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ref', '0009_alter_originator_nom_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originator',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='originator',
            name='ordre',
        ),
        migrations.AddField(
            model_name='originator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='originator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
