# Generated by Django 5.2.17 on 2026-08-07 04:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('core_ref', '0010_alter_originator_options_remove_originator_ordre_and_more'),
        ('documents', '0001_initial'),
        ('projects', '0003_alter_migrationconteneurlog_options_and_more'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Ex: référence, livrable, préalable', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document lié à la tâche',
            },
        ),
        migrations.CreateModel(
            name='TacheLien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lien', models.CharField(choices=[('FS', 'Fin → Début'), ('SS', 'Début → Début'), ('FF', 'Fin → Fin'), ('SF', 'Début → Fin')], default='FS', max_length=2)),
                ('decalage_jours', models.IntegerField(default=0, help_text='Lag positif/négatif en jours')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lien de tâche',
            },
        ),
        migrations.AlterModelOptions(
            name='tache',
            options={'ordering': ['projet', 'commande', 'niveau', 'date_debut_prevue'], 'verbose_name': 'Tâche'},
        ),
        migrations.AddField(
            model_name='tache',
            name='niveau',
            field=models.PositiveSmallIntegerField(default=1, help_text='Calculé : 1 si racine, sinon parent.niveau + 1', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='tache',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Tâche parente (WBS). Niveau 1 = racine. 1..5 remonte en planning_project, 6..n opérationnel seul.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='tasks.tache'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='avancement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tache',
            name='poids',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='tache',
            constraint=models.CheckConstraint(condition=models.Q(('poids__gte', 0), ('poids__lte', 100)), name='tache_poids_0_100'),
        ),
        migrations.AddConstraint(
            model_name='tache',
            constraint=models.CheckConstraint(condition=models.Q(('avancement__gte', 0), ('avancement__lte', 100)), name='tache_avancement_0_100'),
        ),
        migrations.AddConstraint(
            model_name='tache',
            constraint=models.CheckConstraint(condition=models.Q(('niveau__gte', 1)), name='tache_niveau_gte_1'),
        ),
        migrations.AddField(
            model_name='tachedocument',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tachedocument',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_liees', to='documents.document'),
        ),
        migrations.AddField(
            model_name='tachedocument',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_lies', to='tasks.tache'),
        ),
        migrations.AddField(
            model_name='tachelien',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tachelien',
            name='tache_cible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_entrants', to='tasks.tache'),
        ),
        migrations.AddField(
            model_name='tachelien',
            name='tache_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_sortants', to='tasks.tache'),
        ),
        migrations.AlterUniqueTogether(
            name='tachedocument',
            unique_together={('tache', 'document')},
        ),
        migrations.AddConstraint(
            model_name='tachelien',
            constraint=models.CheckConstraint(condition=models.Q(('tache_source', models.F('tache_cible')), _negated=True), name='lien_no_self'),
        ),
        migrations.AlterUniqueTogether(
            name='tachelien',
            unique_together={('tache_source', 'tache_cible', 'type_lien')},
        ),
    ]
