# Generated by Django 6.0.6 on 2026-07-06 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('probabilite', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('statut', models.CharField(choices=[('Ouvert', 'Ouvert'), ('En cours', 'En cours'), ('Clôturé', 'Clôturé'), ('Accepté', 'Accepté')], default='Ouvert', max_length=30)),
                ('plan_mitigation', models.TextField(blank=True)),
                ('date_identification', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='contracts.commande')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risques', to='projects.projet')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Risque',
                'ordering': ['-probabilite', '-impact'],
            },
        ),
    ]
