# Generated by Django 6.0.6 on 2026-07-26 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('core_ref', '0010_alter_originator_options_remove_originator_ordre_and_more'),
        ('projects', '0003_alter_migrationconteneurlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_documentaire', models.CharField(max_length=50, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('revision_actuelle', models.CharField(default='A', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_emission', models.DateTimeField(blank=True, null=True)),
                ('est_archive', models.BooleanField(default=False)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.classedocumentaire')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='contracts.commande')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.discipline')),
                ('origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.originator')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.phase')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.projet')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('statut_actuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.statutcyclevie')),
                ('type_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.doctypetechnique')),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(max_length=10)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('code_retour', models.CharField(blank=True, help_text='Accepté sans commentaire / Rejeté, etc.', max_length=50)),
                ('commentaire', models.TextField(blank=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_ref.statutcyclevie')),
            ],
            options={
                'ordering': ['date_emission'],
            },
        ),
    ]
