"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
PMO EPC Platform — Django Settings
"""

from pathlib import Path
import os

# =============================================================
# CHEMINS DE BASE
# =============================================================
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = backend/core/
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/



# =============================================================
# SÉCURITÉ
# =============================================================
# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-mw+2x-sy*lc@)phq$6!*opk*brkexz0k(hl05uc44n%&ke22wg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = []



# =============================================================
# APPLICATIONS
# =============================================================
# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

]

# Third Party Apps
THIRD_PARTY_APPS = [

    'django_filters',
    'django_tables2',
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',
    'guardian',
]


# Local Apps
LOCAL_APPS = [
    # Local apps
    'apps.accounts',
    'apps.dashboard',
    'apps.documents',
    'apps.projects',
    'apps.contracts',
    'apps.workflows',
    'apps.tasks',
    'apps.costs',
    'apps.risks',
    'apps.reporting',
]


INSTALLED_APPS = (
        DJANGO_APPS
        + THIRD_PARTY_APPS
        + LOCAL_APPS
)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'


# =============================================================
# TEMPLATES
# =============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.parent / 'templates',
            # backend/templates/
        ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core_ref.context_processors.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# =============================================================
# BASE DE DONNÉES
# =============================================================
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'pmo_epc_db',
        'USER': 'postgres',
        'PASSWORD': 'openpgpwd',
        'HOST': 'localhost',
        'PORT': '5433',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# =============================================================
# AUTHENTIFICATION
# =============================================================
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_USER_MODEL = 'accounts.User'
#
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/auth/login/'


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
]


# =============================================================
# INTERNATIONALISATION
# =============================================================
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Libreville'
USE_I18N = True
USE_TZ = True


# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True





# =============================================================
# FICHIERS STATIQUES
# =============================================================
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR.parent / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR.parent / 'static',
    # backend/static/
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"




# =============================================================
# MEDIA (uploads)
# =============================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR.parent / 'media'

# =============================================================
# MESSAGES
# =============================================================
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG:   'alert-secondary',
    messages.INFO:    'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR:   'alert-danger',
}

# =============================================================
# PAGINATION
# =============================================================
DEFAULT_PAGE_SIZE = 25

# =============================================================
# PMO CONFIG
# =============================================================
PMO_CONFIG = {
    'APP_NAME': 'PMO EPC Platform',
    'APP_VERSION': '1.0.0',
    'COMPANY_NAME': 'GED-SERVICES',
    'DEFAULT_REVIEW_DURATION_COMPANY': 15,
    'DEFAULT_REVIEW_DURATION_CONTRACTOR': 15,
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'