DEFAULT_PAGE_SIZE = 25

VIEW_PROJET = "projet"
VIEW_COMMANDE = "commande"
VIEW_RESPONSABLE = "responsable"

EXPORT_EXCEL = "xlsx"
EXPORT_CSV = "csv"
EXPORT_PDF = "pdf"

COLOR_RETARD = "#dc3545"
COLOR_EN_COURS = "#fd7e14"
COLOR_TERMINE = "#198754"
COLOR_ATTENTE = "#0d6efd"
COLOR_DEFAULT = "#6c757d"