# Generated by Django 6.0.6 on 2026-07-06 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core_ref', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_commande', models.CharField(max_length=50, unique=True)),
                ('code_originator', models.CharField(max_length=4)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('contractor', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('Ouvert', 'Ouvert'), ('En cours', 'En cours'), ('En attente', 'En attente'), ('Suspendu', 'Suspendu'), ('Terminée', 'Terminée'), ('Annulée', 'Annulée')], default='Ouvert', max_length=30)),
                ('priorite', models.CharField(blank=True, choices=[('Critique', 'Critique'), ('Haute', 'Haute'), ('Moyenne', 'Moyenne'), ('Basse', 'Basse')], max_length=30)),
                ('date_debut_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_debut_reelle', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('budget_reel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('poids', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('progression_calculee', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duree_revue_company_defaut', models.IntegerField(default=15)),
                ('duree_revue_contractor_defaut', models.IntegerField(default=15)),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('earned_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('est_generique', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_crees', to=settings.AUTH_USER_MODEL)),
                ('entite_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.entite')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_modifies', to=settings.AUTH_USER_MODEL)),
                ('pays', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.pays')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.phase')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='projects.projet')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL)),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.secteur')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_ref.site')),
            ],
            options={
                'verbose_name': 'Commande',
                'ordering': ['projet', 'code_commande'],
            },
        ),
    ]
